args <- commandArgs(TRUE)
library(phylobase)
library(parallel)
library(methods)
#t <- data(geospiza)
source('RSnowtreewalk.R')
#plot(as(geospiza,"phylo4"), show.node.label=TRUE)
s <- ape::read.tree(file=args[1])
t <- as(s,"phylo")
cls <- makeCluster(4)

for (i in 1:5){
    #x <- sample(labels(geospiza),2,replace=TRUE)
    x <- sample(t$node.label,2)
    #print(class(t))
    #print(t$node.label)
    cat("real answer",x[1], x[2],"\n")
    #print(shortestPath(t, x[1], x[2]))
    print(system.time(shortestPath(t, x[1], x[2])))
    cat("RSnow", x[1], x[2],"\n")
    #print(RSnowshortestPath(t, x[1], x[2], cls))
    print(system.time(RSnowshortestPath(t, x[1], x[2], cls)))
    cat("\n\n")
}
stopCluster(cls)
